[package]
name = "doorkeeper"
version = "0.1.0"
edition = "2021"

[features]
default = ["http"]
http = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.5"
json = "0.12.4"

